# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v7.0.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: en_US
odoo_listdb: true
odoo_oci_image: ""
odoo_proxy: ""
odoo_version: 16.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "15"
project_author: ParanaStillus
project_license: BSL-1.0
project_name: stillus
smtp_default_from: ""
smtp_relay_host: ""
