# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v9.0.3
_src_path: gh:Tecnativa/doodba-copier-template
backup_deletion: false
backup_dst: boto3+s3://paranastillus/odoo16
backup_email_from: ""
backup_email_to: ""
backup_image_version: latest
backup_tz: UTC
cidr_whitelist: null
domains_prod:
  - hosts:
      - eip.paranastillus.com
domains_test:
  - hosts:
      - test.paranastillus.com
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: pt_BR
odoo_listdb: false
odoo_listdb_staging: false
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 16.0
paths_with_crawlers:
  - /web/image/website
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "16"
project_author: Stillus
project_license: BSL-1.0
project_name: doodba16-odoo
smtp_default_from: ""
smtp_relay_host: ""
traefik_version: 2
