version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        DB_VERSION: "16"
        ODOO_VERSION: "16.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: ""
      PGDATABASE: &dbname prod
      PGUSER: &dbuser "odoo"
      PROXY_MODE: "true"
    tty: true
    volumes:
      - filestore:/var/lib/odoo:z
    labels:
      traefik.backend.buffering.retryExpression: IsNetworkError() && Attempts() < 5
      traefik.docker.network: "inverseproxy_shared"
      traefik.frontend.passHostHeader: "true"
      traefik.port: "8069"

  db:
    image: ghcr.io/tecnativa/postgres-autoconf:16-alpine
    shm_size: 4gb
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_USER: *dbuser
      CONF_EXTRA: |
        work_mem = 512MB
    volumes:
      - db:/var/lib/postgresql/data:z

  smtpfake:
    image: docker.io/mailhog/mailhog

  backup:
    image: ghcr.io/tecnativa/docker-duplicity-postgres-s3:latest
    hostname: backup.eip.paranastillus.com
    init: true
    environment:
      DB_VERSION: "16"
      DBS_TO_INCLUDE: "^prod"
      DST: "boto3+s3://paranastillus/odoo16"
      PGDATABASE: *dbname
      PGUSER: *dbuser
      TZ: "UTC"
    volumes:
      - backup_cache:/root:z
      - filestore:/mnt/backup/src/odoo:z
