version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    hostname: "prod.docker.local"
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
      ODOO_BUS_PUBLIC_SAMESITE_WS: 1
      PGHOST: doodba16-odoo-16-0-prod-db
    depends_on:
      - db
    networks:
      default:
      inverseproxy_shared:
    labels:
      doodba.domain.main: "prod.docker.local"
      traefik.enable: "true"
      traefik.domain: "prod.docker.local"
      traefik.forbiddenCrawlers-0.frontend.headers.customResponseHeaders:
        "X-Robots-Tag:noindex, nofollow"
      traefik.forbiddenCrawlers-0.frontend.rule: Host(`prod.docker.local`);Path:/web,/web/{anything:.*},/website/info,/website/info/{anything:.*}
      traefik.main-0.frontend.rule: Host(`prod.docker.local`)
      traefik.longpolling-0.frontend.rule: Host(`prod.docker.local`);Path:/websocket,/websocket/{anything:.*}
      traefik.longpolling-0.port: 8072
      traefik.http.middlewares.doodba16-odoo-16-0-prod-buffering.buffering.retryExpression:
        IsNetworkError() && Attempts() < 5
      traefik.http.middlewares.doodba16-odoo-16-0-prod-compress.compress: "true"
      traefik.http.middlewares.doodba16-odoo-16-0-prod-forbid-crawlers.headers.customResponseHeaders.X-Robots-Tag:
        "noindex, nofollow"
      traefik.http.middlewares.doodba16-odoo-16-0-prod-addSTS.headers.forceSTSHeader: "true"
      traefik.http.middlewares.doodba16-odoo-16-0-prod-forceSecure.redirectScheme.scheme: https
      traefik.http.middlewares.doodba16-odoo-16-0-prod-forceSecure.redirectScheme.permanent: "true"
      traefik.http.services.doodba16-odoo-16-0-prod-main.loadbalancer.server.port: 8069
      traefik.http.services.doodba16-odoo-16-0-prod-longpolling.loadbalancer.server.port: 8072
      traefik.http.routers.doodba16-odoo-16-0-prod-main-0.rule: Host(`prod.docker.local`)
      traefik.http.routers.doodba16-odoo-16-0-prod-main-0.service: doodba16-odoo-16-0-prod-main
      traefik.http.routers.doodba16-odoo-16-0-prod-main-0.middlewares:
        doodba16-odoo-16-0-prod-addSTS, doodba16-odoo-16-0-prod-buffering,
        doodba16-odoo-16-0-prod-compress, doodba16-odoo-16-0-prod-forceSecure
      traefik.http.routers.doodba16-odoo-16-0-prod-main-secure-0.rule: Host(`prod.docker.local`)
      traefik.http.routers.doodba16-odoo-16-0-prod-main-secure-0.service: doodba16-odoo-16-0-prod-main
      traefik.http.routers.doodba16-odoo-16-0-prod-main-secure-0.middlewares:
        doodba16-odoo-16-0-prod-addSTS, doodba16-odoo-16-0-prod-buffering,
        doodba16-odoo-16-0-prod-compress, doodba16-odoo-16-0-prod-forceSecure
      traefik.http.routers.doodba16-odoo-16-0-prod-main-secure-0.tls: "true"
      traefik.http.routers.doodba16-odoo-16-0-prod-main-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.doodba16-odoo-16-0-prod-longpolling-0.rule:
        Host(`prod.docker.local`) && Path(`/websocket`)
      traefik.http.routers.doodba16-odoo-16-0-prod-longpolling-0.service: doodba16-odoo-16-0-prod-longpolling
      traefik.http.routers.doodba16-odoo-16-0-prod-longpolling-0.middlewares:
        doodba16-odoo-16-0-prod-addSTS, doodba16-odoo-16-0-prod-forceSecure
      traefik.http.routers.doodba16-odoo-16-0-prod-longpolling-secure-0.rule:
        Host(`prod.docker.local`) && Path(`/websocket`)
      traefik.http.routers.doodba16-odoo-16-0-prod-longpolling-secure-0.service: doodba16-odoo-16-0-prod-longpolling
      traefik.http.routers.doodba16-odoo-16-0-prod-longpolling-secure-0.middlewares:
        doodba16-odoo-16-0-prod-addSTS, doodba16-odoo-16-0-prod-forceSecure
      traefik.http.routers.doodba16-odoo-16-0-prod-longpolling-secure-0.tls: "true"
      traefik.http.routers.doodba16-odoo-16-0-prod-longpolling-secure-0.tls.certResolver: letsencrypt
      traefik.http.routers.doodba16-odoo-16-0-prod-forbiddenCrawlers-0.rule:
        Host(`prod.docker.local`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.doodba16-odoo-16-0-prod-forbiddenCrawlers-0.service: doodba16-odoo-16-0-prod-main
      traefik.http.routers.doodba16-odoo-16-0-prod-forbiddenCrawlers-0.middlewares:
        doodba16-odoo-16-0-prod-addSTS, doodba16-odoo-16-0-prod-buffering,
        doodba16-odoo-16-0-prod-compress, doodba16-odoo-16-0-prod-forbid-crawlers,
        doodba16-odoo-16-0-prod-forceSecure
      traefik.http.routers.doodba16-odoo-16-0-prod-forbiddenCrawlers-secure-0.rule:
        Host(`prod.docker.local`) && (PathPrefix(`/web/`, `/website/info/`) ||
        Path(`/web`, `/website/info`))
      traefik.http.routers.doodba16-odoo-16-0-prod-forbiddenCrawlers-secure-0.service: doodba16-odoo-16-0-prod-main
      traefik.http.routers.doodba16-odoo-16-0-prod-forbiddenCrawlers-secure-0.middlewares:
        doodba16-odoo-16-0-prod-addSTS, doodba16-odoo-16-0-prod-buffering,
        doodba16-odoo-16-0-prod-compress, doodba16-odoo-16-0-prod-forbid-crawlers,
        doodba16-odoo-16-0-prod-forceSecure
      traefik.http.routers.doodba16-odoo-16-0-prod-forbiddenCrawlers-secure-0.tls: "true"
      traefik.http.routers.doodba16-odoo-16-0-prod-forbiddenCrawlers-secure-0.tls.certResolver: letsencrypt

  db:
    extends:
      file: common.yaml
      service: db
    environment:
      - DB_HOST=doodba16-odoo-16-0-prod-db
    env_file:
      - .docker/db-creation.env
    restart: unless-stopped
    networks:
      default:
        aliases:
          - "doodba16-odoo-16-0-prod-db"

networks:
  default:
    driver_opts:
      encrypted: 1

  inverseproxy_shared:
    external: true

volumes:
  filestore:
  db:
